W8D1/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only:[:create, :new, :destroy]
  resources :users do 
    resources :subs, only:[:edit, :update]
    resources :posts, only:[:edit, :update]
  end
  resources :subs, except:[:edit, :update]
  resources :posts, except:[:index, :edit, :update]
end

W8D1/reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string
#  url        :string
#  content    :string
#  sub_id     :integer
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
    validates :title, :sub_id, presence: true

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User 

    belongs_to :sub

    
end

W8D1/reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string
#  description  :string
#  moderator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
    validates :title, presence: true, uniqueness: true

    belongs_to :moderator,
        foreign_key: :moderator_id,
        class_name: :User

    has_many :posts
    
end

W8D1/reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string
#  password_digest :string
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    validates :username, :password_digest, presence: true
    validates :password, length: {minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token

    attr_reader :password

    has_many :subs,
        foreign_key: :moderator_id,
        class_name: :Sub

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64(16)
        self.save!
        self.session_token
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        user && user.is_password?(password) ? user : nil
    end
end

W8D1/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login(user)
        @current_user = user 
        session[:session_token] = user.session_token
    end

    def logout
        current_user.reset_session_token!
        @current_user = nil
        session[:session_token] = nil
    end

    def logged_in?
        !current_user.nil?
    end

    def require_login
        redirect_to new_session_url unless logged_in?
    end

    def is_moderator?(moderator_id)
        current_user.id == moderator_id
    end

end

W8D1/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :require_login, only:[:destroy]

    def new
        render :new # render log in page
    end 

    def create
        # look for valid logins in db
        @user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
        )
        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            flash[:errors] = ['Invalid username or password']
            render :new   # send back to sign in page
        end
    end 

    def destroy
        logout 
        redirect_to new_session_url
    end

end

W8D1/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_login, except:[:show, :index] # anyone can access and see a subreddit
    # before_action only:[:edit, :update] { is_moderator?(params[:moderator_id]) }
    
    def new
        @sub = Sub.new 
        render :new
    end 

    def create
    end 

    def edit
        @sub = current_user.subs.find_by(id: params[:id])
    end 

    def update
    end 

    def destroy
        @sub = current_user.subs.find_by(id: params[:id])
        if @sub
            @sub.destroy
            redirect_to user_url(current_user)
        else  
            flash[:errors] = ['You are not the moderator. Permission is denied']
            redirect_to sub_url(@sub)
        end
    end 

    def show
    end 

    def index
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

W8D1/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only:[:edit]

    def new
        @user = User.new 
        render :new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else  
            flash[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def edit
        @user = User.find_by(id: params[:id])
        render :edit
    end

    def update
        @user = User.find_by(id: params[:id])
        if !@user.update(user_params)
            flash[:errors] = @user.errors.full_messages
        end
        redirect_to user_url(@user)
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end 

    def index
        @users = User.all
        render :index
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

W8D1/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% unless logged_in? %>
        <a href="<%= new_session_url %>">Sign In</a>
      <% end %>
      
    </div>
    <%= yield %>
  </body>
</html>

W8D1/reddit_clone/app/views/users/new.html.erb
<h2>Sign Up</h2>
<form action="<%= users_url %>" method="POST">
    <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>"
    >
    <label>Username:
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>
    <label>Password:
        <input type="password" name="user[password]" value="<%= @user.password %>">
    </label>
    <input type="submit" value="Sign In">
</form>

W8D1/reddit_clone/app/views/users/show.html.erb
<!-- logout button -->
<% if logged_in? && current_user == @user %>
    <form action="<%= session_url %>" method="POST">
        <input type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>"
        >
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Sign Out">
    </form>
<% end %>

<!-- shows user's -->
<h2><%= @user.username %></h2>
<h2>Moderated Subs</h2>
    <ul>
        <% @user.subs.each do |sub| %>
            <a href="<%= user_sub_url(sub) %>"> 
                <%= sub.title %>
            </a>
        <% end %>
    </ul>

<h2>Posts</h2>